PrestamoLibros/Models/PRESTAMO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestamoLibros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTAMO
    {
        public int IdPrestamo { get; set; }
        public Nullable<int> IdLibro { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FecPrestamo { get; set; }
        public Nullable<System.DateTime> FecDevolucion { get; set; }
    
        public virtual LIBRO LIBRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}

PrestamoLibros/Controllers/PrestamoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;
using PrestamoLibros.Models;

namespace PrestamoLibros.Controllers
{
    public class PrestamoController : Controller
    {
        // GET: Categories
        #region Contexto

        private PrestamoLibroEntities _contexto;

        public PrestamoLibroEntities contexto
        {
            set { _contexto = value; }
            get
            {
                if (_contexto == null)
                    _contexto = new PrestamoLibroEntities();
                return _contexto;
            }
        }
        #endregion

        public ActionResult Index()
        {
            return View(contexto.PRESTAMO.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(PRESTAMO nuevoPrestamo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    contexto.PRESTAMO.Add(nuevoPrestamo);
                    contexto.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View(nuevoPrestamo);
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            PRESTAMO PrestamoEditar = contexto.PRESTAMO.Find(id);

            if (PrestamoEditar == null)
                return HttpNotFound();

            return View(PrestamoEditar);
        }

        [HttpPost]
        public ActionResult Edit(PRESTAMO PrestamoEditar)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    contexto.Entry(PrestamoEditar).State = EntityState.Modified;
                    contexto.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View(PrestamoEditar);
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            PRESTAMO PrestamoEliminar = contexto.PRESTAMO.Find(id);

            if (PrestamoEliminar == null)
                return HttpNotFound();

            return View(PrestamoEliminar);
        }

        [HttpPost]
        public ActionResult Delete(int? id, PRESTAMO Prestamo1)
        {
            try
            {
                PRESTAMO PrestamoEliminar = new PRESTAMO();
                if (ModelState.IsValid)
                {
                    if (id == null)
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                    PrestamoEliminar = contexto.PRESTAMO.Find(id);

                    if (PrestamoEliminar == null)
                        return HttpNotFound();

                    contexto.PRESTAMO.Remove(PrestamoEliminar);
                    contexto.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View(PrestamoEliminar);
            }
            catch
            {
                return View();
            }
        }
    }
}

PrestamoLibros/Views/Prestamo/Create.cshtml
@model PrestamoLibros.Models.PRESTAMO
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.IdPrestamo) </label>
        @*Html.EditorFor(model => model.IdPrestamo)*@
        @*Html.ValidationMessageFor(model => model.IdPrestamo)*@
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.IdLibro) </label>
        @Html.EditorFor(model => model.IdLibro)
        @Html.ValidationMessageFor(model => model.IdLibro)
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.IdUsuario) </label>
        @Html.EditorFor(model => model.IdUsuario)
        @Html.ValidationMessageFor(model => model.IdUsuario)
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.FecPrestamo) </label>
        @Html.EditorFor(model => model.FecPrestamo)
        @Html.ValidationMessageFor(model => model.FecPrestamo)
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.FecDevolucion) </label>
        @Html.EditorFor(model => model.FecDevolucion)
        @Html.ValidationMessageFor(model => model.FecDevolucion)
    </div>

    <div class="col-auto">
        <input type="submit" class="btn btn-primary mb-3" value="Create" />
    </div>

}

<div>
    @Html.ActionLink("Ir al índice de prestamos", "Index", "Prestamos", null, null)
</div>

PrestamoLibros/Views/Prestamo/Delete.cshtml
@model PrestamoLibros.Models.PRESTAMO
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">@Html.DisplayNameFor(model => model.IdPrestamo) </label>
    <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.IdPrestamo) </label>
</div>
<div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">@Html.DisplayNameFor(model => model.IdLibro) </label>
    <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.IdLibro) </label>
</div>
<div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">@Html.DisplayNameFor(model => model.IdUsuario) </label>
    <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.IdUsuario) </label>
</div>
<div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">@Html.DisplayNameFor(model => model.FecPrestamo) </label>
    <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.FecPrestamo) </label>
</div>
<div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">@Html.DisplayNameFor(model => model.FecDevolucion) </label>
    <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.FecDevolucion) </label>
</div>




@using (Html.BeginForm())
{
    <div class="col-auto">
        <input type="submit" class="btn btn-primary mb-3" value="Delete" />
    </div>
}

<div>
    @Html.ActionLink("Ir al índice de prestamos", "Index", "Prestamos", null, null)
</div>

PrestamoLibros/Views/Prestamo/Edit.cshtml
@model PrestamoLibros.Models.PRESTAMO
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.IdPrestamo) </label>
        @Html.EditorFor(model => model.IdPrestamo)
        @Html.ValidationMessageFor(model => model.IdPrestamo)
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.IdLibro) </label>
        @Html.EditorFor(model => model.IdLibro)
        @Html.ValidationMessageFor(model => model.IdLibro)
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.IdUsuario) </label>
        @Html.EditorFor(model => model.IdUsuario)
        @Html.ValidationMessageFor(model => model.IdUsuario)
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.FecPrestamo) </label>
        @Html.EditorFor(model => model.FecPrestamo)
        @Html.ValidationMessageFor(model => model.FecPrestamo)
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">@Html.LabelFor(model => model.FecDevolucion) </label>
        @Html.EditorFor(model => model.FecDevolucion)
        @Html.ValidationMessageFor(model => model.FecDevolucion)
    </div>

    <div class="col-auto">
        <input type="submit" class="btn btn-primary mb-3" value="Save" />
    </div>

}

<div>
    @Html.ActionLink("Ir al índice de prestamos", "Index", "Prestamos", null, null)
</div>

PrestamoLibros/Views/Prestamo/Index.cshtml
@model IEnumerable<PrestamoLibros.Models.PRESTAMO>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<p>
    @Html.ActionLink("Nuevo Prestamo", "Create", "Prestamo", null, null)
</p>
<table class="table table-dark table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdPrestamo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdLibro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdUsuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FecPrestamo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FecDevolucion)
        </th>
        <th>

        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPrestamo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdLibro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdUsuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FecPrestamo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FecDevolucion)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.IdPrestamo }) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.IdPrestamo })
            </td>
        </tr>
    }
</table>